Extension of the mouseClick function
faaxm/spix pull request #103
Opened 2024-03-11 10:56 UTC by 53845714nF

Add new parameters (proportion and offset) to the mouseClick function. For the end User this will end in two new Functions `mouseClickWithProportion` and `mouseClickWithOffset`.  It will be possible to click e.g. sliderarea at certain positions.

<img src="https://github.com/faaxm/spix/assets/48125666/f4688441-669f-430f-a569-8cc0c7298475" width="400"/>

Can be used in Python, for example, as follows:
```python
from xmlrpc.client import ServerProxy

session = ServerProxy('http://localhost:9000')
session.mouseClickWithProportion('mainWindow/sliderarea', 0.4, 0.5)
```

2024-03-30 02:51 UTC, faaxm commented
Thank you for your PRs @53845714nF ! I just want you to know that I am aware of them, but that I am super busy at the moment and it might take a while until I can have a proper look at them.

2024-03-30 14:44 UTC, 53845714nF commented
No problem, I already suspected that. 
I'm happy that it was noticed. I will take a look at the clang error.

Happy Easter holidays.

2024-04-17 14:28 UTC, 53845714nF commented
I hope I solve the Clang Error.

2024-05-11 17:00 UTC, faaxm requested changes
Looks good 👍.
Could you merge in your pipeline fixes to stop the ci pipeline from failing? Once that runs through it can be merged :)

2024-05-11 17:00 UTC, faaxm commented on examples/GTestMouseClickPosition/main.cpp
> +TEST(GTestExample, ToMuchProportion)
it's supposed to be "too much", right?
```suggestion
TEST(GTestExample, TooMuchProportion)
```

2024-05-12 08:11 UTC, faaxm commented
just closing and reopening to have github rebase on latest master

2024-05-12 08:26 UTC, 53845714nF commented
I renamed it.

2024-05-12 08:30 UTC, faaxm approved these changes
Nice and thanks for putting in the effort 👍 Hope I soon find time for the remaining reviews... Doing this purely in my free time, so unfortunately spix doesn't always make it to the top of my priority list.

2024-05-12 08:31 UTC, merged