Mouse click with shift and crtl
faaxm/spix pull request #108
Opened 2024-03-26 13:07 UTC by 53845714nF

Adding the capability to also click modifier keys during mouse click. Cloud be useful in Application where you have to select each element.

2025-04-09 09:32 UTC, 53845714nF commented
I have resolved the merge conflicts.

2025-04-09 21:29 UTC, faaxm requested changes
Please have a look at my suggested changes. Otherwise: nice as usual :)

2025-04-09 21:29 UTC, faaxm commented on lib/src/AnyRpcServer.cpp
> +        [this](std::string path, int mouseButton, int keyModifier = KeyModifiers::None) {
I don't think the default parameter works for AnyRPC and the rpc method always expects three arguments.
```suggestion
        "mouseClickWithButton(string path, int mouseButton, int keyModifier)",
        [this](std::string path, int mouseButton, int keyModifier) {
```

2025-04-09 21:29 UTC, faaxm commented on examples/GTest/main.qml
> +                        resultsView.appendText("Button 1 shift control clicked")
This confused me for way longer that I would like to admit ;-)
```suggestion
                        resultsView.appendText("Button 1 control clicked")
```

2025-04-10 09:02 UTC, 53845714nF commented on lib/src/AnyRpcServer.cpp
> +        [this](std::string path, int mouseButton, int keyModifier = KeyModifiers::None) {
I think you know more about AnyRPC than I do. As a Python developer, I think default parameters are cool.

2025-04-10 09:05 UTC, 53845714nF commented on examples/GTest/main.qml
> +                        resultsView.appendText("Button 1 shift control clicked")
That was too long ago for me to comment. But I think it fits.

2025-04-10 09:33 UTC, faaxm approved these changes

2025-04-10 09:34 UTC, merged