Find objects by id
faaxm/spix pull request #34
Opened 2021-06-14 08:58 UTC by krussjos

I didn't like how you have to set an objectName for every single item you want to control. Added some code to allow finding objects by object id. If an objectName is found, id takes priority over the item id.

2021-06-14 09:12 UTC, m-kuhn reviewed
Thanks.

If you add "Fixes #33" to the pull request message, it will automatically close the issue on merge.

2021-06-14 09:12 UTC, m-kuhn commented on lib/src/Scene/Qt/QtItemTools.cpp
> +				if(object->objectName() != "")
```suggestion
				if(!object->objectName().isEmpty())
```

2021-06-15 11:28 UTC, faaxm commented
Generally support the idea but have to find some time to properly review it.

Please run clang-format (there's a script in `./devtools`). Normally the travis-ci build would detect this, but I realise that one's broken right now.

2021-06-15 13:14 UTC, krussjos commented
> clang
Done. Sorry should've have done so before.

2021-06-16 21:38 UTC, faaxm requested changes
Really cool! Just had a few comments. Hope you don't mind my style nit-picking 😉

2021-06-16 21:38 UTC, faaxm commented on lib/src/Scene/Qt/QtItemTools.cpp
> +#include <iostream>
I think this include is not needed anymore.

2021-06-16 21:38 UTC, faaxm commented on lib/src/Scene/Qt/QtItemTools.cpp
> +QString getObjectId(QObject* object)
Minor thing, but please change this function name to be capitalized, so that it is more in line with the other freestanding functions. (just for consistency's sake)
Might also make sense to rename it to "GetObject**Name**", as the id is referred to as "Name" by Qt as well (i.e. you get it from the `nameForObject` call).

```suggestion
QString GetObjectName(QObject* object)
```

2021-06-16 21:38 UTC, faaxm commented on lib/src/Scene/Qt/QtItemTools.cpp
> -
again minor, but I really like having an empty line before the namespaces end ;-)

2021-06-16 21:38 UTC, faaxm commented on lib/src/Scene/Qt/QtItemTools.h
> -
same here: again minor, but I really like having an empty line before the namespaces end ;-)

2021-06-16 21:38 UTC, faaxm commented on lib/src/Scene/Qt/QtItemTools.cpp
> +    return object->objectName();
Please move this `return` into the `if (object != nullptr)` branch to avoid `nullptr` dereferencing when it is actually `null` and maybe turn this into an empty string.

You could also have a nullptr check in the beginning to have the remaining stuff a little less nested/indented, but I'm fine either way. Like:
```
    if (object == nullptr) {
        return ""
    }

    // Allow to override id with objectName
    if (!object->objectName().isEmpty()) {
        return object->objectName();
    }
    QQmlContext* const context = qmlContext(object);
    if (context) {
        return context->nameForObject(object);
    }

    // Fallback if item id is not found
    return object->objectName();
```

2021-06-17 06:00 UTC, krussjos commented on lib/src/Scene/Qt/QtItemTools.cpp
> +    return object->objectName();
Hi,

Good suggestions, I've made the according changes.

2021-06-17 10:54 UTC, faaxm commented on lib/src/Scene/Qt/QtItemTools.cpp
> -
@krussjos please re-add an empty line here (between the includes and the `namespace`) and run clang-format. I think your IDE uses tabs rather than spaces which shows further down at the beginning of `GetObjectName`. Would have changed it myself but I think I cannot push to your fork.

2021-06-17 11:16 UTC, krussjos commented on lib/src/Scene/Qt/QtItemTools.cpp
> -
Hi,

You're very specific the formatting :): I've added the line and also re-run clang-format.

I'm using CLion with the settings for our team at work. Do you want any the tabs to be changed to spaces?

2021-06-17 12:25 UTC, faaxm approved these changes
Beautiful! And thank you so much for the work 😃

2021-06-17 12:27 UTC, faaxm commented on lib/src/Scene/Qt/QtItemTools.cpp
> -
Sorry about that, I wouldn't have complained about the empty line if I hadn't also noticed the tabs ;-)
Thank you for taking the time to fix all the stuff :)

2021-06-17 12:28 UTC, merged